apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/c/mongodb
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
